#!/usr/bin/env ruby

require_relative "src/init_cmd"
require_relative "src/install_cmd"
require_relative "src/list_cmd"
require_relative "src/refresh_cmd"
# require_relative "src/reorder"

command = ARGV[0]

case command
when "init"
  InitCmd.new.run
when "install"
  InstallCmd.new.run
when "list"
  ListCmd.new.run
when "refresh"
  RefreshCmd.new.run
when "reorder"
  # reorder_cmd
else
  puts "Unknown command #{command}"
end
